package GUI;


import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author admin
 */
public class View_Schedule extends javax.swing.JFrame {

    /**
     * Creates new form View_Schedule
     */
    public View_Schedule() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 398, 17));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("SCHEDULE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 280, -1));

        jLabel2.setText("ICT  F");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 20));

        jLabel3.setText("ICT A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 40, -1));

        jLabel4.setText("ICT  C");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 40, 30));

        jLabel5.setText("ICT B");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 40, -1));

        jLabel7.setText("ICT  D");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 40, -1));

        jLabel9.setText("ICT  E");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 40, -1));

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 398, 17));

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 400, 17));

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 398, 17));

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 398, 17));

        jButton6.setText("jButton1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 398, 17));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
             JOptionPane.showMessageDialog(
    null,
    "Tuesday:\n" +
    "  • EAPP 2:00pm–4:00pm (Room 406)",
    "  • Inquiries 4:00pm–6:00pm\n" +
    "Wednesday:\n" +
    "  • P.E 1:00pm–2:00pm (ANNEX 2)\n\n" +
    "  • Conarts 2:00am–3:30pm\n" +
    "  • Entrep 3:30pm–5:00pm\n" +
    
    "Friday:\n" +
   "  • Comprog 7:30am–11:30am (CL3)\n\n" +
    "",
    JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
             JOptionPane.showMessageDialog(
    null,
    "Monday:\n" +
    "  • EAPP 8:00am–10:00am (4063)\n\n" +
    "  • Inquiries 10:00am–12:00pm (4063)\n\n" +
            "Wednesday:\n" +
    "  • Entrep 8:00am–9:30am\n" +
    "  • Conarts 9:30am–11:00am\n" +
    "  • P.E 11:00am–12:00pm (ANNEX 2)\n\n" +
    "Thursday:\n" +
    "  • Comprog 7:30am–11:30am\n" +
    
    JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
             JOptionPane.showMessageDialog(
    null,
    "Monday:\n" +
    "  • Comprog 7:30pm–11:30am (CL3)\n\n" +
    "Wednesday:\n" +
    "  • P.E 8:00am–9:00am (405)\n\n" +
    "  • Entrep 9:00am–10:30am\n" +
    "  • Conarts 10:30am–12:30pm\n" +
    "Friday:\n" +
    "  • Inquiries 7:30am–10:00am\n" +
    "  • EAPP 10:00am–11:30am (a2)",
    "",
    JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
             JOptionPane.showMessageDialog(
    null,
    "Tuesday:\n" +
    "  • Comprog 2:00pm–6:00pm (CL3)\n\n" +
    "Thursday:\n" +
    "  • Conarts 11:30am–1:00pm\n" +
    "  • Entrep 1:00pm–2:30pm\n" +
    "  • P.E 2:30pm–3:30pm (ANNEX 2)\n\n" +
    "Friday:\n" +
    "  • Inquiries 1:30pm–3:30pm\n" +
    "  • EAPP 3:30pm–5:30pm (Room 406)",
    "",
    JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
             JOptionPane.showMessageDialog(
    null,
    "Monday:\n" +
    "  • Comprog 2:00pm–6:00pm (CL3)\n\n" +
    "Thursday:\n" +
    "  • Conarts 11:30am–1:00pm\n" +
    "  • Entrep 1:00pm–2:30pm\n" +
    "  • P.E 2:30pm–3:30pm (ANNEX 2)\n\n" +
    "Friday:\n" +
    "  • ??? 1:30pm–3:30pm\n" +
    "  • EAPP 3:30pm–5:30pm (Room 406)",
    "",
    JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
             JOptionPane.showMessageDialog(
    null,
    "Tuesday:\n" +
    "  • Comprog 2:00pm–6:00pm (CL3)\n\n" +
    "Thursday:\n" +
    "  • Conarts 11:30am–1:00pm\n" +
    "  • Entrep 1:00pm–2:30pm\n" +
    "  • P.E 2:30pm–3:30pm (ANNEX 2)\n\n" +
    "Friday:\n" +
    "  • ??? 1:30pm–3:30pm\n" +
    "  • EAPP 3:30pm–5:30pm (Room 406)",
    "",
    JOptionPane.INFORMATION_MESSAGE
);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
